# Generated by Django 3.1.4 on 2022-03-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duckmodel',
            name='src',
            field=models.CharField(default='<django.db.models.fields.CharField>.jpeg', max_length=30),
        ),
        migrations.AlterField(
            model_name='duckmodel',
            name='species',
            field=models.CharField(choices=[('Indian Runner Duck', 'Indian Runner'), ('Mallard Duck', 'Mallard'), ('Pekin Duck', 'Pekin'), ('Khaki Campbell', 'Khaki Campbell'), ('Buff', 'Buff'), ('Magpie', 'Magpie')], max_length=30),
        ),
    ]
